<a href="https://colab.research.google.com/github/OvertheSkyy/My-AWS-ML-AI-Learning-Path/blob/main/AWS_First_ML_AI_Workshop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**AWS** CLOUD PUP MANILA 𝐅𝐢𝐫𝐬𝐭 𝐌𝐋/𝐀𝐈 𝐖𝐨𝐫𝐤𝐬𝐡𝐨𝐩

traditional approach

In [ ]:
myName = "Sung Jinwoo"
myAge = 25

print("My name is", myName, "and I am", myAge, "years old.")

My name is Sung Jinwoo and I am 25 years old.


f-string approach - more concise

In [ ]:
myName = "Gaeus Caskie"
myAge = 20

print(f"My name is {myName} and I am {myAge} years old.")

My name is Gaeus Caskie and I am 20 years old.


Python Arrays

In [ ]:
intArr = [1, 0, 1, 2]
print(intArr)

[1, 0, 1, 2]


Python Operations

In [ ]:
division = 10/3

print(f"Division result: {division:.2f}") # '.2f' to limit decimal places

Division result: 3.33


Conditional statements

In [ ]:
given_number = 0
number_to_compare = 1

if given_number == number_to_compare:
  print(f"Given number, {given_number} is equal to {number_to_compare}")

For and while loops

In [ ]:
for i in range(5):
  print("I'm a for loop.")

I'm a for loop.
I'm a for loop.
I'm a for loop.
I'm a for loop.
I'm a for loop.


In [ ]:
# while_loop = 2

# while while_loop != 0:
#   print("I'm a while loop.")

Iterate elements in List

In [ ]:
my_list = ["Computer", "Engineering", "Department"]

for elements in my_list:
  print(elements)

Computer
Engineering
Department


Functions

In [ ]:
def addition(first_number, second_number):
    sum = first_number + second_number

    return sum

result = addition(5, 3)

result

8

##Libraries

Numpy - numerical python

In [ ]:
import numpy as np

In [ ]:
#1D zeros

zeros_1d = np.zeros(10)
zeros_1d

#1D ones
ones_1d = np.ones(10)
ones_1d

#2D zeros
columns = 2
rows = 5

zeros_2d = np.zeros((rows, columns)) # TUPLE {}
zeros_2d

#2D ones
ones_2d = np.ones((rows, columns))
ones_2d


#1D full
full_1d = np.full((10), 42)
full_1d

array([42, 42, 42, 42, 42, 42, 42, 42, 42, 42])

Check if value is not a number (NaN)

In [ ]:
import numpy as np
import random

nan_val = np.NaN


if np.isnan(nan_val) == True:
  print("The variable is NaN.")
else:
  print("The variable is not NaN.")

The variable is NaN.


Check if value is infinity/infinite

In [ ]:
inf_val = np.inf

if np.isinf(inf_val) == True:
  print("The variable is infinity")
else:
  print("The variable is not inifinity")

The variable is infinity


Create array using numpy

In [ ]:
np_array = np.array([1, 2, 3, 4, 5]) #input is list

np_array

first_row = [1, 2, 3]
second_row = [4, 5, 6]

two_dimensional_array = np.array([first_row,
                                  second_row])
two_dimensional_array

two_dimensional_array.shape

(2, 3)

Step -




In [ ]:
#Create an array using '.arange()'

starting_number = 0
ending_number = 41
step = 1
array_with_arange = np.arange(starting_number, ending_number, step)

array_with_arange


#Create an array using '.linspace()'
starting_number = 0
ending_number = 40
amount_to_generate = 41
array_with_linspace = np.linspace(starting_number,
                                  ending_number,
                                  amount_to_generate)

array_with_linspace

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40.])

In [ ]:
upper_bound = 6
size_1 = 2
size_2 = 5

random_array = np.random.randint(upper_bound, size=(size_1, size_2))

random_array

array([[5, 2, 2, 0, 1],
       [2, 5, 0, 1, 3]])

In [ ]:
# Create array with values between 0 and 1
random_distribution = np.random.rand(2, 5)

# Create an array within a certain interval
size = (2, 5)
random_uniform_array = np.random.uniform(3, 5, size)
random_uniform_array_transformed = random_uniform_array.astype(np.intc) #use of .astype to convert array to another data type

random_uniform_array_transformed

array([[3, 3, 4, 3, 4],
       [3, 4, 4, 3, 3]], dtype=int32)

Append, Insert, Delete for numpy array

In [ ]:
#Append
my_array = np.array([0, 1, 2, 3, 4, 8])

numbers_to_append = [9, 10]
my_array_appended = np.append(my_array, numbers_to_append)

my_array_appended

#Insert
index = 5
numbers_to_insert = [5, 6, 7]
my_array_inserted = np.insert(my_array, index, numbers_to_insert)
my_array_inserted

#Delete
index = 5
my_array_deleted = np.delete(my_array, index)
my_array_deleted

array([0, 1, 2, 3, 4])

2D Array - Matrix

In [ ]:
matrix_1 = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])

matrix_2 = np.array([[9, 10, 11, 12],
                     [13, 14, 15, 16]])

concatenated_row_wise = np.concatenate((matrix_1, matrix_2),
                                        axis=0) #row wise

concatenated_column_wise = np.concatenate((matrix_1, matrix_2),
                                        axis=1) #column wise

concatenated_column_wise


#Using stack

stacked_matrix = np.stack((matrix_1, matrix_2))
stacked_matrix

#Using split
num_arrays_to_split = 2
splitted_matrix_row_wise = np.split(concatenated_row_wise, num_arrays_to_split, axis=0) #row wise
splitted_matrix_column_wise = np.split(concatenated_column_wise, num_arrays_to_split, axis=1) #column wise

splitted_matrix_column_wise

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

Seed

In [ ]:
np.random.seed(42)

random_array = np.random.rand(5, 2)
random_array

# Check array shape
random_array_shape = random_array.shape

random_array_shape


# Check number of dimensions
random_array_ndimensions = random_array.ndim

# Check total size of array
random_array_size = random_array.size
random_array_size

10

Slicing

In [ ]:
np.random.seed(42)
random_array = np.random.randint(20, size=(5, 5))

element = random_array[4, 1]

elements_in_row = random_array[3, :]

elements_in_column = random_array[:, 1]

elements_within_row = random_array[0, 1:4]

elements_within_column = random_array[0:3, 1]
elements_within_column


array([19, 18,  2])

Transpose (row to column)

In [ ]:
np.random.seed(42)

random_array = np.random.randint(20, size=(2, 5))

random_array_transposed = random_array.transpose(1, 0) #swap (2, 5) to (5, 2)
random_array_transposed

array([[ 6,  6],
       [19, 18],
       [14, 10],
       [10, 10],
       [ 7,  3]])

Reshape

In [ ]:
random_array_reshape = random_array.reshape(5, 2)
random_array_reshape

array([[ 6, 19],
       [14, 10],
       [ 7,  6],
       [18, 10],
       [10,  3]])

Flatten

In [ ]:
random_array_flatten = random_array.flatten()
random_array_flatten

array([ 6, 19, 14, 10,  7,  6, 18, 10, 10,  3])