<a href="https://colab.research.google.com/github/OvertheSkyy/My-AWS-ML-AI-Learning-Path/blob/main/Workshop_1_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Workshop #1 Exercise
##### You can visit the notebook for reference: https://github.com/AWS-MLAI/AWS-Cloud-Cloud-PUP-Manila-ML-AI/blob/master/Workshop%231_assets/Workshop_1.ipynb

# But before starting, please make a copy of this notebook where you will be writing your code for this workshop. To do this, please follow the steps shown by the image provided below.

<img src= "https://github.com/AWS-MLAI/AWS-Cloud-Cloud-PUP-Manila-ML-AI/blob/master/Images/Saving_a_copy.png?raw=true" height=600 width=1000/>

# When you are done with the task/s on your notebook please make share that your notebook is accessible by following the steps shown by the image provided below.

<img src="https://github.com/AWS-MLAI/AWS-Cloud-Cloud-PUP-Manila-ML-AI/blob/master/Images/Sharing_notebook.png?raw=true" height=500 width=1000>

# Then paste the link of your notebook at Google Classroom for submission.

**PYTHON SYNTAX EXCERCISES (1-7)**



### 1. Create a `myName` variable and `myAge` variable and print it using python formatting
#### Sample output: `My name is Roljohn Frilles and I am 20 years old`

In [83]:
myName = "Sung Jinwoo"
myAge = 24

print(f"My name is {myName} and I am {myAge} years old")

My name is Sung Jinwoo and I am 24 years old


### 2. Create an array of float and an array of strings both with size 3




In [84]:
random_float = [300.25, 655.76, 1782.78]
hi_diff_countries = ["Hi", "Bonjour", "Nǐn hǎo"]

print(f"Array of float: {random_float}")
print(f"Array of ways to say hi in different countries (strings): {hi_diff_countries}")

Array of float: [300.25, 655.76, 1782.78]
Array of ways to say hi in different countries (strings): ['Hi', 'Bonjour', 'Nǐn hǎo']


### 3. Using the two variables `x` and `y` as operands given below, perform basic arithmetic operations, specifically addition, subtraction, multiplication, and division, then assign each to variable, and print them after.

In [85]:
# Given operands
x = 20
y = 5

# Your code
sum = x + y
difference = x - y
product = x * y
quotient = x / y

print(f"Here are the results, sum: {sum}, difference: {difference}, product: {product}, quotient:{quotient}")

Here are the results, sum: 25, difference: 15, product: 100, quotient:4.0


## 4. Create a conditional statement to compare variables `myNumber` and `yourNumber`. Then make a print statement to determine whether `myNumber` is greater than `yourNumber` or vice versa.

In [86]:
# Variables to compare
myNumber = 12
yourNumber = 68


# Your conditional statement
if yourNumber > myNumber:
  print(f"My number, {yourNumber}, is greater than your number, {myNumber}.")

My number, 68, is greater than your number, 12.


## 5. Make a for loop statement to print a sequence of values from 0 to 4 using `range()`

In [87]:
for i in range(5):
  print(i)

0
1
2
3
4


## 6. Create a list with elements `["Artificial Intelligence", "Machine Learning", "Deep Learning"]`, then Iterate and print each element of the list using for loop

In [88]:
ai_elements = ["Artificial Intelligence", "Machine Learning", "Deep Learning"]


# Your for loop statement
for i in ai_elements:
  print(i)

Artificial Intelligence
Machine Learning
Deep Learning


## 7. Create a function that multiply two numbers, and returns the product.

In [89]:
def product(num1, num2):
    return num1 * num2

result = product(2, 3)

print(f"Product: {result}")

Product: 6


**NUMPY EXERCISES**

## 1. Import the `numpy` library as `np`, and Create 1D arrays of ones and zeros both with size `10`

In [90]:
import numpy as np

zeros_1D_arr = np.zeros(10)

ones_1D_arr = np.ones(10)

#check array elements
print(f"My zeros 1D array: \n{zeros_1D_arr}\n \n My ones 1D array: \n{ones_1D_arr}\n")

My zeros 1D array: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 
 My ones 1D array: 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]



## 2. Create 2D arrays of ones and zeros both with shape (3, 4)

In [91]:
zeros_two_dim_arr = np.zeros((3,4))

ones_two_dim_arr = np.ones((3,4))

#check array elements
print(f"My zeros 2D array: \n{zeros_two_dim_arr}\n \n My ones 2D array: \n{ones_two_dim_arr}\n")

My zeros 2D array: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
 My ones 2D array: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]



## 3. Create a 2D array filled with a specific value `42` with shape (3, 4).

In [92]:
specific_value = 42

my_2D_arr = np.full((3,4), specific_value)

# Check 2D array
print(f"My 2D array: \n{my_2D_arr}")

My 2D array: 
[[42 42 42 42]
 [42 42 42 42]
 [42 42 42 42]]


## 4. Create a variable named `nan_variable` and assign it a `nan` value, then check whether the variable `nan_variable` contains a `nan` value.



In [93]:
nan_variable = np.NaN # Assign a NaN value to variable `nan_value`

if np.isnan(nan_variable) == True:
  print("The nan_variable has a NaN value.")

The nan_variable has a NaN value.


## 5. Create a variable named `inf_variable` and assign it an `inf` value, then check whether the variable `inf_variable` contains an `inf` value.


In [94]:
inf_variable = np.inf # Assign a inf value to variable `inf_value`
if np.isinf(inf_variable) == True:
  print("The inf_variable has a inf value.")

The inf_variable has a inf value.


## 6. Create an array based on the instruction below.

In [95]:
# Create a 1D array with size 5
one_dim_arr = np.array([1, 2, 3, 4, 5])

# Check 1D array
print(f"1D array with size 5: \n {one_dim_arr}\n")

# Create a 2D array with shape (2x4)
two_dim_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(f"2D array with size 2x4: \n {two_dim_arr}\n")

1D array with size 5: 
 [1 2 3 4 5]

2D array with size 2x4: 
 [[1 2 3 4]
 [5 6 7 8]]




## 7. Create random values based on the instruction provided below:

In [96]:
# Create a random array with an upper limit of 10 (numbers between 0-10) with shape (4x2)
np.random.seed(1)

upper_bound = 10

random_array = np.random.randint(upper_bound, size=(4,2))
print(f"Random array: \n{random_array}\n")

# Create a random array with values ranging 0-1 using `np.random.rand()` with shape (4x2)
random_array = np.random.rand(4,2)
print(f"Random array: \n{random_array}\n")

Random array: 
[[5 8]
 [9 5]
 [0 0]
 [1 7]]

Random array: 
[[0.34556073 0.39676747]
 [0.53881673 0.41919451]
 [0.6852195  0.20445225]
 [0.87811744 0.02738759]]




## 8. Convert the given array's datatype below into integers

In [97]:
import numpy as np

np.random.seed(42)
given_array = np.random.uniform(10, size=(4, 2))

# Your code
given_array_transformed = given_array.astype(np.intc)

print(f"Given array: \n{given_array}\n")
print(f"Converted given array: \n{given_array_transformed}")

Given array: 
[[6.62913893 1.44357124]
 [3.41205452 4.61207364]
 [8.59583224 8.59604932]
 [9.47724749 2.20441469]]

Converted given array: 
[[6 1]
 [3 4]
 [8 8]
 [9 2]]


## 9. Append the values `25` and `2` respectively to the given array below

In [98]:
import numpy as np

given_array = np.array([9, 2, 1, 7])

val_to_append = [25, 2]
val_array_appended = np.append(given_array, val_to_append)
print(f"Updated Array values: {val_array_appended}\n")

Updated Array values: [ 9  2  1  7 25  2]



## 10. Create your own two 2D arrays, then follow the instructions provided below

In [99]:
# Your first 2D array
first_matrix = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

# Your second 2D array
second_matrix = np.array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30], [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

# Concatenate your two arrays column-wise
concatenated_column_wise = np.hstack((first_matrix, second_matrix))
print(f"Concatenated arrays column-wise: \n{concatenated_column_wise}\n")

# Stack your two arrays
stacked_matrix = np.stack((first_matrix, second_matrix))
print(f"Stacked arrays: \n{stacked_matrix}\n")

# Split your two arrays into 3 arrays row-wise

concatenated_row_wise = np.vstack((first_matrix, second_matrix))
split_to_three = 3
split_matrix_row_wise = np.array_split(concatenated_row_wise, split_to_three, axis=0)

print(f"Row-wise array: \n{concatenated_row_wise}\n")
print(f"Row-wise splitted array: \n{split_matrix_row_wise}\n")

Concatenated arrays column-wise: 
[[ 1  2  3  4  5  6  7  8  9 10 21 22 23 24 25 26 27 28 29 30]
 [11 12 13 14 15 16 17 18 19 20 31 32 33 34 35 36 37 38 39 40]]

Stacked arrays: 
[[[ 1  2  3  4  5  6  7  8  9 10]
  [11 12 13 14 15 16 17 18 19 20]]

 [[21 22 23 24 25 26 27 28 29 30]
  [31 32 33 34 35 36 37 38 39 40]]]

Row-wise array: 
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]

Row-wise splitted array: 
[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]), array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]]), array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])]



## 11. Create a random seed with argument value `42`, and create a random array using `np.random.rand()` with shape (2x4), then follow the instructions provided below

In [106]:
# Create a random seed
np.random.seed(2)

# Create a random array with `np.random.rand()` with shape (2x4)
random_array = np.random.rand(2, 4)

# Print the size of the array
print(f"Size of random array: {random_array.size}")

# Print the shape of the array
print(f"Shape of random array: {random_array.shape}")

# Print the datatype of the array
print(f"Data type of random array: {random_array.dtype}")

# Print the number of dimensions the array has
print(f"Number of dimensions of random array: {random_array.ndim}")

Size of random array: 8
Shape of random array: (2, 4)
Data type of random array: float64
Number of dimensions of random array: 2


## 12. Manipulate the dimensions of the given array with shape (2x5) based on the instructions provided below

In [120]:
import numpy as np

np.random.seed(42)

# Given random array with shape (2x5)
random_array = np.random.randint(10, size=(2, 5))
print(f"Random array {random_array.shape}: \n{random_array}\n")

# Swap the two dimension size from (2x5) to (5x2)
random_array_transposed = random_array.transpose(1,0)
print(f"Transposed random array {random_array_transposed.shape}: \n{random_array_transposed}\n")

# Reshape the array from (2x5) to (10x1)
random_array_reshaped = random_array.reshape(10, 1)
print(f"Shape of random array reshaped: {random_array_reshaped.shape}\n")

# Flatten the array
random_array_flattened = random_array.flatten()
print(f"Flattened random array: {random_array_flattened}")


Random array (2, 5): 
[[6 3 7 4 6]
 [9 2 6 7 4]]

Transposed random array (5, 2): 
[[6 9]
 [3 2]
 [7 6]
 [4 7]
 [6 4]]

Shape of random array reshaped: (10, 1)

Flattened random array: [6 3 7 4 6 9 2 6 7 4]


## 13. Find the largest and smallest value of the given array based on the instructions provided below

In [122]:
import numpy as np

np.random.seed(42)

# Given array
random_array = np.random.randint(100, size=(4, 5))

# Take the largest value of the ENTIRE of the array
largest_value_entire = np.max(random_array)
print(f"Largest value found in the entire random array: {largest_value_entire}")

# Take the smallest value of EACH ROW of the array
smallest_value_row = np.min(random_array, axis=1)
print(f"Smallest value found in each row of random array: {smallest_value_row}")

Largest value found in the entire random array: 99
Smallest value found in each row of random array: [14 20  2  1]


## 14. Perform arithmetic operations using the two arrays provided below

In [130]:
import numpy as np

# First array
first_array = np.array([5, 2, 10, 4])

# Second array
second_array = np.array([21, 52, 7, 10])

# Add the two arrays
sum_two_arr = first_array + second_array
print(f"Sum of the two arrays: {sum_two_arr}\n")

# Subtract the two arrays
difference_two_arr = first_array - second_array
print(f"Difference of the two arrays: {difference_two_arr}\n")

# Multiply the two arrays
product_two_arr = first_array * second_array
print(f"Product of the two arrays: {product_two_arr}\n")

# Divide the two arrays
quotient_two_arr = first_array / second_array
print(f"Quotient of the two arrays: {quotient_two_arr}")

Sum of the two arrays: [26 54 17 14]

Difference of the two arrays: [-16 -50   3  -6]

Product of the two arrays: [105 104  70  40]

Quotient of the two arrays: [0.23809524 0.03846154 1.42857143 0.4       ]


Submitted by: Gaeus Caskie Fabro