<a href="https://colab.research.google.com/github/OvertheSkyy/My-AWS-ML-AI-Learning-Path/blob/main/Workshop_1_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Workshop #1 Exercise
##### You can visit the notebook for reference: https://github.com/AWS-MLAI/AWS-Cloud-Cloud-PUP-Manila-ML-AI/blob/master/Workshop%231_assets/Workshop_1.ipynb

# But before starting, please make a copy of this notebook where you will be writing your code for this workshop. To do this, please follow the steps shown by the image provided below.

<img src= "https://github.com/AWS-MLAI/AWS-Cloud-Cloud-PUP-Manila-ML-AI/blob/master/Images/Saving_a_copy.png?raw=true" height=600 width=1000/>

# When you are done with the task/s on your notebook please make share that your notebook is accessible by following the steps shown by the image provided below.

<img src="https://github.com/AWS-MLAI/AWS-Cloud-Cloud-PUP-Manila-ML-AI/blob/master/Images/Sharing_notebook.png?raw=true" height=500 width=1000>

# Then paste the link of your notebook at Google Classroom for submission.

**PYTHON SYNTAX EXCERCISES (1-7)**



### 1. Create a `myName` variable and `myAge` variable and print it using python formatting
#### Sample output: `My name is Roljohn Frilles and I am 20 years old`

In [2]:
myName = "Sung Jinwoo"
myAge = 24

print(f"My name is {myName} and I am {myAge} years old")

My name is Sung Jinwoo and I am 24 years old


### 2. Create an array of float and an array of strings both with size 3




In [3]:
random_float = [300.25, 655.76, 1782.78]
hi_diff_countries = ["Hi", "Bonjour", "Nǐn hǎo"]

### 3. Using the two variables `x` and `y` as operands given below, perform basic arithmetic operations, specifically addition, subtraction, multiplication, and division, then assign each to variable, and print them after.

In [4]:
# Given operands
x = 20
y = 5

# Your code
sum = x + y
difference = x - y
product = x * y
quotient = x / y

print(f"Here are the results, sum: {sum}, difference: {difference}, product: {product}, quotient:{quotient}")

Here are the results, sum: 25, difference: 15, product: 100, quotient:4.0


## 4. Create a conditional statement to compare variables `myNumber` and `yourNumber`. Then make a print statement to determine whether `myNumber` is greater than `yourNumber` or vice versa.

In [5]:
# Variables to compare
myNumber = 12
yourNumber = 68


# Your conditional statement
if yourNumber > myNumber:
  print(f"My number, {yourNumber}, is greater than your number, {myNumber}.")

My number, 68, is greater than your number, 12.


## 5. Make a for loop statement to print a sequence of values from 0 to 4 using `range()`

In [6]:
for i in range(5):
  print(i)

0
1
2
3
4


## 6. Create a list with elements `["Artificial Intelligence", "Machine Learning", "Deep Learning"]`, then Iterate and print each element of the list using for loop

In [7]:
ai_elements = ["Artificial Intelligence", "Machine Learning", "Deep Learning"]


# Your for loop statement
for i in ai_elements:
  print(i)

Artificial Intelligence
Machine Learning
Deep Learning


## 7. Create a function that multiply two numbers, and returns the product.

In [8]:
def product(num1, num2):
    return num1 * num2

result = product(2, 3)
print(result)

6


**NUMPY EXERCISES**

## 1. Import the `numpy` library as `np`, and Create 1D arrays of ones and zeros both with size `10`

In [9]:
import numpy as np

zeros_1D_arr = np.zeros(10)

ones_1D_arr = np.ones(10)

#check array elements
print(zeros_1D_arr, ones_1D_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## 2. Create 2D arrays of ones and zeros both with shape (3, 4)

In [10]:
zeros_two_dim_arr = np.zeros((3,4))

ones_two_dim_arr = np.ones((3,4))

#check array elements
print(f"{zeros_two_dim_arr}, \n{ones_two_dim_arr}\n")

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]



## 3. Create a 2D array filled with a specific value `42` with shape (3, 4).

In [17]:
specific_value = 42

my_2D_arr = np.full((3,4), specific_value)

# Check 2D array
print(my_2D_arr)

[[42 42 42 42]
 [42 42 42 42]
 [42 42 42 42]]


## 4. Create a variable named `nan_variable` and assign it a `nan` value, then check whether the variable `nan_variable` contains a `nan` value.



In [ ]:
# Your code

## 5. Create a variable named `inf_variable` and assign it an `inf` value, then check whether the variable `inf_variable` contains an `inf` value.


In [ ]:
# Your code

## 6. Create an array based on the instruction below.

In [ ]:
# Create a 1D array with size 5


# Create a 2D array with shape (2x4)


## 7. Create random values based on the instruction provided below:

In [ ]:
# Create a random array with an upper limit of 10 (numbers between 0-10) with shape (4x2)


# Create a random array with values ranging 0-1 using `np.random.rand()` with shape (4x2)


## 8. Convert the given array's datatype below into integers

In [ ]:
import numpy as np

np.random.seed(42)
given_array = np.random.uniform(10, size=(4, 2))

# Your code

## 9. Append the values `25` and `2` respectively to the given array below

In [ ]:
import numpy as np

given_array = np.array([9, 2, 1, 7])

# Your code

## 10. Create your own two 2D arrays, then follow the instructions provided below

In [ ]:
# Your first 2D array

# Your second 2D array

# Concatenate your two arrays column-wise

# Stack your two arrays

# Split your two arrays into 3 arrays row-wise

## 11. Create a random seed with argument value `42`, and create a random array using `np.random.rand()` with shape (2x4), then follow the instructions provided below

In [ ]:
# Create a random seed

# Create a random array with `np.random.rand()` with shape (2x4)

# Print the size of the array

# Print the shape of the array

# Print the datatype of the array

# Print the number of dimensions the array has

## 12. Manipulate the dimensions of the given array with shape (2x5) based on the instructions provided below

In [12]:
import numpy as np

np.random.seed(42)

# Given random array with shape (2x5)
random_array = np.random.randint(10, size=(2, 5))

# Swap the two dimension size from (2x5) to (5x2)

# Reshape the array from (2x5) to (10x1)

# Flatten the array

## 13. Find the largest and smallest value of the given array based on the instructions provided below

In [13]:
import numpy as np

np.random.seed(42)

# Given array
random_array = np.random.randint(100, size=(4, 5))

# Take the largest value of the ENTIRE of the array

# Take the smallest value of EACH ROW of the array

## 14. Perform arithmetic operations using the two arrays provided below

In [14]:
import numpy as np

# First array
first_array = np.array([5, 2, 10, 4])

# Second array
second_array = np.array([21, 52, 7, 10])

# Add the two arrays

# Subtract the two arrays

# Multiply the two arrays

# Divide the two arrays